### ISSUE TITLE
Doesn't seem to want to run on Linux Mint.

### ISSUE THREAD

**Issue by pnunn** [ganeshdipdumbare/gospeedtest#1]
Followed the instructions on the readme, and after installing build-essentials it compiles OK, but seems something is missing. Is this a known issue?

pnunn@MintTest:~$ gospeedtest
gospeedtest: command not found
pnunn@MintTest:~$ go/bin/gospeedtest 
Error: could not start driver: fork/exec /home/pnunn/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: no such file or directory
Alas, there's been an error: could not start driver: fork/exec /home/pnunn/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: no such file or directory

**Comment by ganeshdipdumbare** [comment]
Hi Peter, 
Thanks for letting me know the issue. Can you please try running with latest version as follows - 
`go install github.com/ganeshdipdumbare/gospeedtest@v0.1.2`

**Comment by pnunn** [comment]
Looks as though that did the trick :)

pnunn@MintTest:~$ go/bin/gospeedtest 
2023/02/12 15:48:10 Downloading driver to /home/pnunn/.cache/ms-playwright-go/1.20.0-beta-1647057403000
2023/02/12 15:48:31 Downloaded driver successfully
Downloading Playwright build of chromium v978106 - 130.7 Mb [====================] 100% 0.0s 
Playwright build of chromium v978106 downloaded to /home/pnunn/.cache/ms-playwright/chromium-978106
Downloading Playwright build of ffmpeg v1007 - 2.6 Mb [====================] 100% 0.0s 
Playwright build of ffmpeg v1007 downloaded to /home/pnunn/.cache/ms-playwright/ffmpeg-1007
Downloading Playwright build of firefox v1319 - 75.5 Mb [====================] 100% 0.0s 
Playwright build of firefox v1319 downloaded to /home/pnunn/.cache/ms-playwright/firefox-1319
Downloading Playwright build of webkit v1616 - 78.8 Mb [====================] 100% 0.0s 
Playwright build of webkit v1616 downloaded to /home/pnunn/.cache/ms-playwright/webkit-1616
█  Download speed is: 1.0 Gbps
█  Upload speed is: 570 Mbps

Not seeing bubble tea in action though, but love the results. Thanks heaps for your efforts.

**Comment by ganeshdipdumbare** [comment]
Not an issue. Can you please try running this sample Go program - https://github.com/charmbracelet/bubbletea/blob/master/examples/spinners/main.go
Need to be sure if it is just the issue with the Bubble tea.

**Comment by pnunn** [comment]
OK, that worked. I think I was perhaps expecting more from speetest :) The spinner seems to be working, I think I was expecting a bar chart of some sort or something.

All good.  On one machine though I did get an npx error when I tried to run the binary produced on another machine saying playground was missing some dependencies.. but I'll look at that another time. :)

**Comment by ganeshdipdumbare** [comment]
ah got it. I will add the chart for sure in the near future. 

For running binaries on another machine, the dependencies are always needed to be installed. As it is using headless browser internally so.

For now I will close the issue. :)
